// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Auth struct {
	AuthID    int32
	UserEmail string
	AuthUuid  uuid.UUID
}

type Music struct {
	ID       int32
	Title    string
	Artist   string
	Album    string
	Location string
	Year     int32
}

type User struct {
	UserID         int32
	Email          string
	Username       string
	HashedPassword string
	FirstName      string
	LastName       string
	DateOfBirth    time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Verified       bool
}
