// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: music.sql

package database

import (
	"context"
)

const getMusicByID = `-- name: GetMusicByID :one
SELECT id, title, artist, album, location, year FROM music WHERE id = $1
`

func (q *Queries) GetMusicByID(ctx context.Context, id int32) (Music, error) {
	row := q.db.QueryRowContext(ctx, getMusicByID, id)
	var i Music
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Artist,
		&i.Album,
		&i.Location,
		&i.Year,
	)
	return i, err
}
